version: '3.4'

services:
  webservice:
    image: dev/sonarqube
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env.local
    ports:
      - 3000:3000
      - 80:80
    volumes:
      - ./data:/usr/src/redmine/files

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=redmine
      - POSTGRES_DB=redmine
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./psql:/var/lib/postgresql/data
